# Default values for jenkins.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

global:
  domain: 'devstack.local'

Master:
  Name: jenkins-master
  Image: "kaigara/jenkins"
  ImageTag: "1.0.0"
  ImagePullPolicy: "IfNotPresent"
  Component: "jenkins-master"
  AdminUser: admin
  Cpu: "200m"
  Memory: "256Mi"
  ServicePort: 8080
  ContainerPort: 8080
  SlaveListenerPort: 50000

Agent:
  Image: jenkinsci/jnlp-slave
  ImageTag: 2.52
  Cpu: "200m"
  Memory: "256Mi"

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteOnce
  Size: 8Gi
