{{- if .Values.Persistence.Enabled }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ template "fullname" . }}-etc
  annotations:
    volume.alpha.kubernetes.io/storage-class: {{ .Values.Persistence.StorageClass | quote }}
spec:
  accessModes:
    - {{ .Values.Persistence.AccessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.Persistence.Size | quote }}
{{- end }}
