apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  create-jira-db.sql: |-
    CREATE USER 'jira'@'%' IDENTIFIED BY '{{ .Values.global.jiraDbPassword }}';
    CREATE DATABASE jiradb;
    GRANT ALL PRIVILEGES ON jiradb.* TO 'jira'@'%';
    FLUSH PRIVILEGES;
