# Default values for gerrit.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: gerrit-master
  Image: "gcr.io/hc-public/devstack/gerrit"
  ImageTag: "latest"
  ImagePullPolicy: "Always"
  Component: "gerrit-master"
  AdminUser: admin
  AdminPassword: changeme
  DbPassword: changeme
  ServicePort: 8080
  ServiceType: LoadBalancer
  ContainerPort: 8080
  SshPort: 29418
  GerritHome: "/var/gerrit"
  GerritSite: "/var/gerrit/review_site"
  GerritWar: "/var/gerrit/gerrit.war"

Persistence:
  Enabled: true
  StorageClass: generic
  AccessMode: ReadWriteMany
  Size: 8Gi
