# Declare variables to be passed into your templates.
#
replicaCount: 1
image:
  repository: kaigara/gerrit
  tag: latest
  pullPolicy: Always
service:
  type: ClusterIP
  http:
    externalPort: 8080
    internalPort: 8080
  ssh:
    externalPort: 29418
    internalPort: 29418
resources:
  requests:
    cpu: 1
    memory: 512Mi
  limits:
    cpu: 1
    memory: 1024Mi
persistence:
  enabled: true
  storageClass: generic
  accessMode: ReadWriteMany
  size: 8Gi
auth:
  type: ldap
  server: ldap
  dc: ldap
basePath: "/var/gerrit/review_site/git"
database:
  database: "reviewdb"
  username: "gerrit"
  password: "changeme"
global:
  domain: devstack.local
  mariadbRootPassword: changeme
  LdapAdminPassword: changeme
