apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "fullname" . }}
data:
  gerrit.config: |-
    [gerrit]
      basePath = {{.Values.Master.GerritHome}}
      canonicalWebUrl = http://gerrit.{{.Values.global.domain}}
    [database]
      type = mysql
      hostname = {{ template "dbmaster" . }}
      port = 3306
      database = reviewdb
      username = gerrit2
    [index]
      type = LUCENE
    [auth]
      type = LDAP
    [ldap]
      server = ldap://{{ template "ldap" . }}
      username = cn=admin,dc={{ template "ldap" . }}
      accountBase = ou=people,dc={{ template "ldap" . }}
      groupBase = ou=gerrit,ou=groups,dc={{ template "ldap" . }}
      accountFullName = ${givenName} ${sn}
      accountEmailAddress = ${mail}
    [receive]
      enableSignedPush = false
    [sendemail]
      smtpServer = localhost
    [container]
      user = root
      war = {{.Values.Master.GerritWar}}
    [gitweb]
      cgi = /usr/share/gitweb/gitweb.cgi
    [sshd]
      listenAddress = *:{{.Values.Master.SshPort}}
    [cache]
      directory = cache
  secure.config: |-
    [database]
      password = {{ .Values.Master.DbPassword }}
    [ldap]
      password = {{ .Values.global.LdapAdminPassword }}
  create-gerrit-db.sql: |-
    CREATE USER 'gerrit2'@'%' IDENTIFIED BY '{{ .Values.Master.DbPassword }}';
    CREATE DATABASE reviewdb;
    GRANT ALL PRIVILEGES ON reviewdb.* TO 'gerrit2'@'%';
    FLUSH PRIVILEGES;
