apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  jenkins-admin-password:  {{ .Values.global.JenkinsAdminPassword | b64enc | quote }}
  jenkins-admin-user: {{ .Values.Master.AdminUser | b64enc | quote }}
