apiVersion: extensions/v1beta1
kind: Ingress

metadata:
  namespace: {{ .Values.global.namespace }}
  name: {{ template "fullname" . }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/tls-acme: "true"

spec:
  rules:
  - host: "ldap.{{ .Values.global.domain }}"
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: 80

  tls:
    - secretName: tls-helios-webfront
      hosts:
        - "ldap.{{ .Values.global.domain }}"
