apiVersion: v1
kind: Service
metadata:
  name: {{template "fullname" . }}
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
spec:
  ports:
    - port: {{.Values.Master.ContainerPort}}
      name: http
      targetPort: {{.Values.Master.ContainerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
